- name: copy file
  copy: src=build.openssl.tar.gz dest=/tmp/build.openssl.tar.gz mode=0777

- name: tar file
  shell: cd /tmp && tar xvf build.openssl.tar.gz && rm -rf build.openssl.tar.gz

- name: run install
  shell: "cd /tmp/build.openssl && ./install.sh"
  ignore_errors: yes